# main text of home
name: Hamed Usman
bio: Researcher and Teacher

# twitter summary info
description: Hamed Usman's thoughts, ideas and projects. Here so they can be safely ignored.

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/hu.png
logo: assets/images/hu.png

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: true
resume-url: https://hamedusman.github.io/mycv/extended

url: https://hamedusman.github.io
# your url: http://USERNAME.github.io

# permalink: /:title/
permalink: /blog/:title.html


# To enable google analytics, supply your token below
analytics-google: 'UA-100695591-1'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: mydisqus # enter this from your disqus account
  categories: #[blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
# facebook: myfacebook
#twitter: mytwitter
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: hamedusman
# youtube: myyoutube
#spotify: myspotify
github: hamedusman
# lastfm: mylastfm
# stackoverflow: mystackoverflow
# quora: userquora
# reddit: username
#medium: mymedium
orcid: 0000-0003-3755-9345
# vimeo: myvimeo
# email: myemail@gmail.com

authors:
    elipapa:
        name: Hamed Usman
        bio: Researcher and Teacher
        external-image: false
        picture: assets/images/hu.png
        #twitter:

collections:
  work:
    output: true
    permalink: /:collection/:name

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
# blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
# show-author: true

# do you want some animations?
animation: true

gems:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

jekyll-mentions:
    base_url: https://github.com



# # Permalinks

# # Setup
# title:            Hamed Usman
# tagline:          'Thoughts, ideas and projects. Here so they can be safely ignored.'
# description:      'Researcher, Teacher'
# production_url:   'http://hamedusman.github.io'

# author:
#   name:           'Hamed Usman'
#   url:            'http://hamedusman.github.io'

# paginate:         8
# paginate_path:    "blog/:num"

# # Custom vars
# repo:             "http://github.com/hamedusman/hamedusman.github.io"

# # let github generate a sitemap.xml for you
# gems:
#   - jekyll-sitemap
#   - jekyll-paginate
